{application,cache_server,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{cache_server_app,[]}},
              {env,[]},
              {modules,[cache_server,cache_server_app,cache_server_sup,
                        help_funs]}]}.
